/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deployment */
        get: operations["deployment_api_diagnostics_deployment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/graph-definitions/{definition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Definition */
        get: operations["graph_definition_api_diagnostics_graph_definitions__definition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_diagnostics_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_diagnostics_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/sessions/{session_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Attempts */
        get: operations["session_attempts_api_diagnostics_sessions__session_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turns */
        get: operations["turns_api_diagnostics_sessions__session_id__turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Attempts */
        get: operations["recent_attempts_api_diagnostics_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace */
        get: operations["trace_api_diagnostics_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/traces/{trace_id}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spans */
        get: operations["spans_api_diagnostics_traces__trace_id__spans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/traces/{trace_id}/spans/{span_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Span */
        get: operations["span_api_diagnostics_traces__trace_id__spans__span_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/clarifications/{clarification_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond */
        post: operations["respond_api_sessions__session_id__clarifications__clarification_id__responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_sessions__session_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build */
        get: operations["build_build_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentDeployment */
        AgentDeployment: {
            /** Agent Id */
            agent_id: string;
            /** Graph Definition Id */
            graph_definition_id?: string | null;
            /** Routable */
            routable: boolean;
            /** Version */
            version: string;
        };
        /** AssistantMessage */
        AssistantMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @default assistant
             * @constant
             */
            role: "assistant";
        };
        /** AttemptSummary */
        AttemptSummary: {
            /** Attempted Turn Number */
            attempted_turn_number: number;
            /** Committed Turn Number */
            committed_turn_number?: number | null;
            /** Completed At */
            completed_at?: string | null;
            error?: components["schemas"]["SanitizedExecutionError"] | null;
            /** Input Preview */
            input_preview?: string | null;
            observability_status: components["schemas"]["ObservabilityStatus"];
            request_origin: components["schemas"]["RequestOrigin"];
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Trace Id */
            trace_id: string;
        };
        /** BuildDeployment */
        BuildDeployment: {
            /** Name */
            name: string;
            /** Revision */
            revision: string;
        };
        /** BuildResponse */
        BuildResponse: {
            /** Application Version */
            application_version: string;
            /** Architectural Packages */
            architectural_packages: {
                [key: string]: string;
            };
            deployment: components["schemas"]["BuildDeployment"];
            /** Immutable */
            immutable: boolean;
            /** Repository */
            repository: string;
            /** Source Commit */
            source_commit: string | null;
            /** Uv Lock Sha256 */
            uv_lock_sha256: string | null;
        };
        /**
         * CancelResponse
         * @description Decline the question, always available.
         */
        CancelResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            form: "cancel";
        };
        /** CapturePresence */
        CapturePresence: {
            /**
             * Input
             * @default false
             */
            input: boolean;
            /**
             * Output
             * @default false
             */
            output: boolean;
            /**
             * Resolved Messages
             * @default false
             */
            resolved_messages: boolean;
            /**
             * State Delta
             * @default false
             */
            state_delta: boolean;
        };
        /**
         * CapturedContent
         * @description A controlled inline value, authorized artifact reference, or omission marker.
         */
        CapturedContent: {
            /** Byte Size */
            byte_size?: number | null;
            /** Content Type */
            content_type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            mode: components["schemas"]["ContentCaptureMode"];
            /** Reason */
            reason?: string | null;
            /** Reference Id */
            reference_id?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Value */
            value?: unknown | null;
        };
        /** ChatError */
        ChatError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ChatErrorResponse */
        ChatErrorResponse: {
            error: components["schemas"]["ChatError"];
            /** Session Id */
            session_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            message: components["schemas"]["AssistantMessage"];
            /** Session Id */
            session_id: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["CompletedToolCall"][];
            /** Trace Id */
            trace_id: string;
        };
        /** ClarificationError */
        ClarificationError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ClarificationErrorResponse */
        ClarificationErrorResponse: {
            error: components["schemas"]["ClarificationError"];
            /** Session Id */
            session_id: string;
        };
        /** ClarificationOptionView */
        ClarificationOptionView: {
            /** Detail */
            detail?: string | null;
            /** Label */
            label: string;
            /** Option Id */
            option_id: string;
        };
        /** CompletedToolCall */
        CompletedToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Status
             * @default completed
             * @constant
             */
            status: "completed";
        };
        /**
         * ContentCaptureMode
         * @enum {string}
         */
        ContentCaptureMode: "inline" | "reference" | "omitted";
        /**
         * ContinuationBody
         * @description A submission identifier and exactly one response form.
         */
        ContinuationBody: {
            /** Response */
            response: components["schemas"]["OptionSelectionResponse"] | components["schemas"]["FreeTextResponse"] | components["schemas"]["CancelResponse"];
            /** Submission Id */
            submission_id: string;
        };
        /**
         * ContinuationCompleted
         * @description The committed turn a continuation produced.
         */
        ContinuationCompleted: {
            /**
             * Closed By
             * @enum {string}
             */
            closed_by: "answered" | "canceled";
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
            /** Trace Id */
            trace_id: string;
            /** Turn Number */
            turn_number: number;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** DeploymentDiagnostic */
        DeploymentDiagnostic: {
            /** Agents */
            agents: components["schemas"]["AgentDeployment"][];
            /** Entry Agent */
            entry_agent: string;
            /** Name */
            name: string;
            /** Revision */
            revision: string;
        };
        /** ExceptionObservation */
        ExceptionObservation: {
            /** Exception Module */
            exception_module: string;
            /** Exception Type */
            exception_type: string;
            /**
             * Frames
             * @default []
             */
            frames: components["schemas"]["TracebackFrame"][];
            /** Message */
            message: string;
        };
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "pending" | "running" | "completed" | "failed" | "cancelled" | "skipped";
        /**
         * FailureDetail
         * @description Bounded, redacted internal detail for one failed execution span.
         */
        FailureDetail: {
            /** Exception Chain */
            exception_chain: components["schemas"]["ExceptionObservation"][];
            /** Fingerprint */
            fingerprint: string;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * FreeTextResponse
         * @description Bounded free text, always available whatever the selection mode.
         */
        FreeTextResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            form: "free_text";
            /** Text */
            text: string;
        };
        /** GraphDefinition */
        GraphDefinition: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Hash */
            definition_hash: string;
            /** Definition Id */
            definition_id: string;
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["GraphEdgeDefinition"][];
            /** Entrypoint */
            entrypoint: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNodeDefinition"][];
            /**
             * Schema Version
             * @default 4
             * @constant
             */
            schema_version: 4;
        };
        /** GraphEdgeDefinition */
        GraphEdgeDefinition: {
            /** @default direct */
            kind: components["schemas"]["GraphEdgeKind"];
            /** Label */
            label?: string | null;
            /** Source Node Id */
            source_node_id: string;
            /** Target Node Id */
            target_node_id: string;
        };
        /**
         * GraphEdgeKind
         * @enum {string}
         */
        GraphEdgeKind: "direct" | "conditional";
        /** GraphNodeDefinition */
        GraphNodeDefinition: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Destination Agent Id */
            destination_agent_id?: string | null;
            /** Display Name */
            display_name: string;
            kind: components["schemas"]["GraphNodeKind"];
            /** Node Id */
            node_id: string;
            /**
             * Owner Path
             * @default []
             */
            owner_path: string[];
            prompt_template?: components["schemas"]["PromptTemplateDefinition"] | null;
        };
        /**
         * GraphNodeKind
         * @enum {string}
         */
        GraphNodeKind: "start" | "end" | "deterministic" | "router" | "model" | "tool" | "child_agent" | "subgraph";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryMessage */
        HistoryMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ModelObservation */
        ModelObservation: {
            /** Identity */
            identity?: string | null;
            /** Provider */
            provider?: string | null;
            usage?: components["schemas"]["UsageObservation"] | null;
        };
        /**
         * ObservabilityStatus
         * @description Durability state independent from the outcome of the application turn.
         * @enum {string}
         */
        ObservabilityStatus: "recording" | "complete" | "degraded";
        /**
         * OptionSelectionResponse
         * @description A typed selection of one or more offered option IDs.
         */
        OptionSelectionResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            form: "options";
            /** Option Ids */
            option_ids: string[];
        };
        /** Page[AttemptSummary] */
        Page_AttemptSummary_: {
            /** Items */
            items: components["schemas"]["AttemptSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[SessionSummary] */
        Page_SessionSummary_: {
            /** Items */
            items: components["schemas"]["SessionSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[TurnSummary] */
        Page_TurnSummary_: {
            /** Items */
            items: components["schemas"]["TurnSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * PendingClarification
         * @description One question a session is waiting on, and how it may be answered.
         *
         *     Free text and cancellation are always available, which is why they are stated here as
         *     fixed fields rather than left for a client to infer from the selection mode.
         */
        PendingClarification: {
            /**
             * Cancel Allowed
             * @default true
             */
            cancel_allowed: boolean;
            /** Clarification Id */
            clarification_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Free Text Allowed
             * @default true
             */
            free_text_allowed: boolean;
            /** Options */
            options: components["schemas"]["ClarificationOptionView"][];
            /** Question */
            question: string;
            /** Reason Code */
            reason_code: string;
            /** Selection Mode */
            selection_mode: string;
            /** Session Id */
            session_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /** PromptTemplateDefinition */
        PromptTemplateDefinition: {
            /** Template Id */
            template_id: string;
            /** Template Text */
            template_text: string;
            /** Version */
            version?: string | null;
        };
        /**
         * RequestOrigin
         * @description Descriptive request source; never an authorization signal.
         * @enum {string}
         */
        RequestOrigin: "api" | "diagnostic_ui" | "unknown";
        /** SanitizedExecutionError */
        SanitizedExecutionError: {
            /** Category */
            category?: string | null;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /**
         * SessionHistoryResponse
         * @description Committed conversation, plus the question the session is waiting on if there is one.
         *
         *     `messages` holds committed turns only. An open clarification is not a committed turn
         *     and is projected separately, so a reader cannot mistake a question still being asked
         *     for part of the immutable history.
         */
        SessionHistoryResponse: {
            /** Durable */
            durable: boolean;
            /** Messages */
            messages: components["schemas"]["HistoryMessage"][];
            pending_clarification?: components["schemas"]["PendingClarification"] | null;
            /** Session Id */
            session_id: string;
            /** Storage */
            storage: string;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Agent Id */
            agent_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Title */
            display_title: string;
            /** Revision */
            revision: number;
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SpanDetail */
        SpanDetail: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            captures: components["schemas"]["CapturePresence"];
            /** Caused By Span Ids */
            caused_by_span_ids: string[];
            /** Completed At */
            completed_at?: string | null;
            /** Definition Node Id */
            definition_node_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            error?: components["schemas"]["SanitizedExecutionError"] | null;
            failure_detail?: components["schemas"]["FailureDetail"] | null;
            /** Graph Definition Id */
            graph_definition_id?: string | null;
            input?: components["schemas"]["CapturedContent"] | null;
            /** Iteration */
            iteration: number;
            kind: components["schemas"]["SpanKind"];
            model?: components["schemas"]["ModelObservation"] | null;
            output?: components["schemas"]["CapturedContent"] | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Prompt Template Id */
            prompt_template_id?: string | null;
            resolved_messages?: components["schemas"]["CapturedContent"] | null;
            /** Scheduler Triggers */
            scheduler_triggers?: string[];
            /** Sequence Completed */
            sequence_completed?: number | null;
            /** Sequence Started */
            sequence_started: number;
            /** Span Id */
            span_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state_delta?: components["schemas"]["CapturedContent"] | null;
            status: components["schemas"]["ExecutionStatus"];
            /** Superstep */
            superstep: number;
            tool?: components["schemas"]["ToolObservation"] | null;
        };
        /**
         * SpanKind
         * @enum {string}
         */
        SpanKind: "turn" | "graph" | "node" | "model" | "tool" | "child_agent";
        /** SpanSummary */
        SpanSummary: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version: string;
            captures: components["schemas"]["CapturePresence"];
            /** Caused By Span Ids */
            caused_by_span_ids: string[];
            /** Completed At */
            completed_at?: string | null;
            /** Definition Node Id */
            definition_node_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            error?: components["schemas"]["SanitizedExecutionError"] | null;
            /** Graph Definition Id */
            graph_definition_id?: string | null;
            /** Iteration */
            iteration: number;
            kind: components["schemas"]["SpanKind"];
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Prompt Template Id */
            prompt_template_id?: string | null;
            /** Sequence Completed */
            sequence_completed?: number | null;
            /** Sequence Started */
            sequence_started: number;
            /** Span Id */
            span_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Superstep */
            superstep: number;
        };
        /** ToolObservation */
        ToolObservation: {
            /** Tool Id */
            tool_id?: string | null;
        };
        /** TraceDetail */
        TraceDetail: {
            /** Agent Versions */
            agent_versions: {
                [key: string]: string;
            };
            /** Application Version */
            application_version: string;
            /** Attempted Turn Number */
            attempted_turn_number: number;
            /** Committed Turn Number */
            committed_turn_number?: number | null;
            /** Completed At */
            completed_at?: string | null;
            /** Core Version */
            core_version: string;
            /** Deployment Version */
            deployment_version: string;
            error?: components["schemas"]["SanitizedExecutionError"] | null;
            /** Input Preview */
            input_preview?: string | null;
            observability_status: components["schemas"]["ObservabilityStatus"];
            request_origin: components["schemas"]["RequestOrigin"];
            /** Root Span Id */
            root_span_id: string;
            /** Sequence Completed */
            sequence_completed?: number | null;
            /** Sequence Started */
            sequence_started: number;
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Trace Id */
            trace_id: string;
        };
        /** TracebackFrame */
        TracebackFrame: {
            /** Filename */
            filename: string;
            /** Function */
            function: string;
            /** Line Number */
            line_number: number;
        };
        /** TurnSummary */
        TurnSummary: {
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
            input: components["schemas"]["ConversationMessage"];
            response: components["schemas"]["ConversationMessage"];
            /**
             * Routing Outcome
             * @enum {string}
             */
            routing_outcome: "answer" | "delegate" | "clarify" | "reject";
            /** Selected Agent Id */
            selected_agent_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /** Turn Number */
            turn_number: number;
        };
        /** UsageObservation */
        UsageObservation: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Orchestration-Origin"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingClarification"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatErrorResponse"];
                };
            };
        };
    };
    deployment_api_diagnostics_deployment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentDiagnostic"];
                };
            };
        };
    };
    graph_definition_api_diagnostics_graph_definitions__definition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_api_diagnostics_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_diagnostics_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_attempts_api_diagnostics_sessions__session_id__traces_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttemptSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turns_api_diagnostics_sessions__session_id__turns_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TurnSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_attempts_api_diagnostics_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttemptSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_api_diagnostics_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spans_api_diagnostics_traces__trace_id__spans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    span_api_diagnostics_traces__trace_id__spans__span_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
                span_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_api_sessions__session_id__clarifications__clarification_id__responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                clarification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinuationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContinuationCompleted"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingClarification"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationErrorResponse"];
                };
            };
        };
    };
    history_api_sessions__session_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_build_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
