"""Typed in-process child-agent invocation boundary."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Protocol

from langchain_core.messages import BaseMessage

from orchestration_core.clarification import (
    CONTINUATION_CONTRACT_VERSION,
    ClarificationRequest,
    ClarificationResponse,
)
from orchestration_core.observability import ExecutionContext


@dataclass(frozen=True, slots=True)
class AgentDescriptor:
    """Routing-safe metadata for one eligible child agent."""

    agent_id: str
    description: str
    capabilities: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class ConversationRequest:
    """Conversation state explicitly supplied to a child agent."""

    messages: tuple[BaseMessage, ...]


@dataclass(frozen=True, slots=True)
class ConversationResult:
    """Messages generated by one successful child invocation."""

    generated_messages: tuple[BaseMessage, ...]


@dataclass(frozen=True, slots=True)
class PausedConversation:
    """A child stopped at a clarification instead of producing a final answer.

    A separate outcome rather than a `ConversationResult` with optional fields, so a
    paused child cannot be mistaken for one that answered: the contract that a completed
    invocation ends in a final assistant message stays true, and a caller must decide what
    to do with a pause instead of reading a message that is not there.

    `graph_definition_id` is the version stamp a resume is checked against. It is the
    identity of the compiled graph's structure, so a deployment that renames or rewires a
    node changes it, and a run paused against the old shape is refused rather than resumed
    into a graph it no longer matches.
    """

    agent_id: str
    run_id: str
    clarification: ClarificationRequest
    queued_clarification_ids: tuple[str, ...] = ()
    graph_definition_id: str | None = None
    continuation_contract_version: int = CONTINUATION_CONTRACT_VERSION


ChildOutcome = ConversationResult | PausedConversation


@dataclass(frozen=True, slots=True)
class ContinuationRequest:
    """One answer offered to the active clarification of a paused run.

    Everything here is checked against the checkpoint before it is applied. The caller's
    copy of the clarification and its freshness token identify which pause is being
    answered; they never replace what the producer actually stored.
    """

    run_id: str
    clarification_id: str
    response: ClarificationResponse
    freshness_token: str
    graph_definition_id: str | None = None
    continuation_contract_version: int = CONTINUATION_CONTRACT_VERSION


@dataclass(frozen=True, slots=True)
class InvocationContext:
    """Non-secret identity and nesting state for one child invocation."""

    execution: ExecutionContext
    caller_agent_id: str
    depth: int = 0


class AgentInvocationError(RuntimeError):
    """A child invocation failed at the controlled runtime boundary."""


class UnknownAgentError(AgentInvocationError):
    """The requested child is not installed in the deployment."""


class ForbiddenAgentError(AgentInvocationError):
    """The caller is not eligible to invoke the requested child."""


class AgentInvocationDepthError(AgentInvocationError):
    """The invocation would exceed the configured nesting limit."""


class AgentInvocationTimeoutError(AgentInvocationError):
    """A child invocation exceeded its runtime deadline."""


class AgentExecutionError(AgentInvocationError):
    """A child graph raised an execution error."""


class InvalidAgentResultError(AgentInvocationError):
    """A child returned a result that violates the conversation contract."""


ContinuationRejection = Literal[
    "missing_checkpoint",
    "not_paused",
    "graph_version",
    "contract_version",
    "unknown_clarification",
    "stale_producer",
]


class ContinuationNotResumableError(AgentInvocationError):
    """A paused run cannot be continued, and the user must start a new request.

    Carries a bounded reason category rather than detail about the stored run, so the
    controlled response and its diagnostic trace can name why a continuation was refused
    without exposing checkpoint contents. Refusing is the whole point: an incompatible
    graph or a stale producer snapshot must not be answered from data that no longer
    describes the run.
    """

    def __init__(self, reason: ContinuationRejection, message: str) -> None:
        super().__init__(message)
        self.reason = reason


class AgentInvoker(Protocol):
    """Invoke an eligible startup-compiled child graph."""

    async def invoke(
        self,
        agent_id: str,
        request: ConversationRequest,
        context: InvocationContext,
    ) -> ChildOutcome: ...
